# Generated by Django 4.2.5 on 2024-02-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_remove_parent_relation_ship_departmenthead_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="id_number",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
