# Generated by Django 4.0.8 on 2024-08-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_student_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_parent',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
