# Generated by Django 4.0.8 on 2024-08-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_user_is_parent_delete_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
