# Generated by Django 4.0.8 on 2024-08-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_user_address_user_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Zone',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
