# Generated by Django 4.0.8 on 2024-08-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_user_address_user_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(choices=[('Head Office', 'Head Office'), ('Unit-I', 'Unit-I'), ('Unit-I&II&III', 'Unit-I&II&III'), ('CMDO', 'CMDO'), ('Unit-II', 'Unit-II'), ('Unit-III', 'Unit-III'), ('Kolkata', 'Kolkata'), ('Delhi', 'Delhi'), ('Chennai', 'Chennai'), ('Mumbai', 'Mumbai'), ('Ahmedabad', 'Ahmedabad'), ('Hyderabad', 'Hyderabad'), ('Bangalore', 'Bangalore'), ('Cochin', 'Cochin'), ('Unit-I & II', 'Unit-I & II'), ('MDO', 'MDO'), ('Pune', 'Pune'), ('Jaipur', 'Jaipur'), ('Indore', 'Indore'), ('Lucknow', 'Lucknow'), ('Bhiwandi', 'Bhiwandi'), ('head Office', 'head Office'), ('Calicut', 'Calicut')], default='Head Office', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_join_in_aludecor',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('CTM-HO', 'CTM-HO'), ('HR', 'HR'), ('Accounts_Finance', 'Accounts_Finance'), ('Stores', 'Stores'), ('WDL', 'WDL'), ('Line_1_3', 'Line_1_3'), ('Coating_Line', 'Coating_Line'), ('Customer Sales Support', 'Customer Sales Support'), ('Taxation', 'Taxation'), ('Commercial', 'Commercial'), ('Warehouse_Logistics', 'Warehouse_Logistics'), ('Quality_Control', 'Quality_Control'), ('Corporate_Sales', 'Corporate_Sales'), ('Project Sales', 'Project Sales'), ('Mechanical', 'Mechanical'), ('Line_2', 'Line_2'), ('Administration', 'Administration'), ('Dispatch', 'Dispatch'), ('PPC', 'PPC'), ('SCM', 'SCM'), ('Accounts', 'Accounts'), ('Sampling', 'Sampling'), ('Electrical', 'Electrical'), ('Export', 'Export'), ('Trade_Marketing', 'Trade_Marketing'), ('CTM-Operations', 'CTM-Operations'), ('CTM-Sales', 'CTM-Sales'), ('PT_Operator', 'PT_Operator'), ('Rewinding_Operator', 'Rewinding_Operator'), ('Procurement', 'Procurement'), ('Line_4_5', 'Line_4_5'), ('Research_Development', 'Research_Development'), ('Legal', 'Legal'), ('FR_Production', 'FR_Production'), ('Coordination', 'Coordination'), ('IT', 'IT'), ('Technical_Support', 'Technical_Support'), ('Design_Application', 'Design_Application'), ('HoneyComb1', 'HoneyComb1'), ('Management Information System', 'Management Information System'), ('Operations', 'Operations'), ('Data Management Executive', 'Data Management Executive'), ('Quality_Assurance', 'Quality_Assurance'), ('Enterprise_Technology', 'Enterprise_Technology'), ('Lab', 'Lab'), ('Project Sales_Product Specification', 'Project Sales_Product Specification'), ('Audit', 'Audit'), ('Process Coordinator', 'Process Coordinator'), ('Virtual Sales', 'Virtual Sales'), ('Management', 'Management'), ('System Developments & Automation', 'System Developments & Automation'), ('Business Management System', 'Business Management System'), ('CRM Application Management', 'CRM Application Management'), ('CSS_CBD of CSS', 'CSS_CBD of CSS'), ('Project Sales_Spec_BD_KAM', 'Project Sales_Spec_BD_KAM'), ('CRM', 'CRM'), ('MIS', 'MIS'), ('EXIM', 'EXIM'), ('SAP', 'SAP'), ('Product Specification', 'Product Specification'), ('Zinc Series', 'Zinc Series'), ('L&D', 'L&D'), ('Online_Quality', 'Online_Quality'), ('Marketing', 'Marketing'), ('Digital Marketing', 'Digital Marketing'), ('Customer Business Development of CSS', 'Customer Business Development of CSS'), ('Brand Activation', 'Brand Activation'), ('Design_Execution', 'Design_Execution'), ('Customer Sales Support_Customer Business Development of CSS', 'Customer Sales Support_Customer Business Development of CSS'), ('Marcom', 'Marcom'), ('Billing', 'Billing'), ('Zinc_Solid_Panel', 'Zinc_Solid_Panel'), ('Line_6', 'Line_6'), ('Tinting', 'Tinting'), ('BD/KAM', 'BD/KAM'), ('Operation_Trainee', 'Operation_Trainee'), ('Lean', 'Lean'), ('ACP_LOUVERS', 'ACP_LOUVERS'), ('Business Strategy_Operation', 'Business Strategy_Operation')], default='CTM-HO', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='zone',
            field=models.CharField(choices=[('Corporate', 'Corporate'), ('Haridwar', 'Haridwar'), ('East', 'East'), ('North', 'North'), ('South', 'South'), ('West', 'West'), ('South & West', 'South & West'), ('Upper_North', 'Upper_North')], default='North', max_length=20),
        ),
    ]
