# Generated by Django 4.0.8 on 2024-09-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_lecturer_learner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reporting_to',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
