# Generated by Django 5.1.1 on 2024-09-24 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0026_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["id"]},
        ),
    ]
