# Generated by Django 5.1.1 on 2024-09-29 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_student_department_alter_learner_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.TextField(blank=True, default=' ', max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='departmenthead',
            name='user',
            field=models.OneToOneField(default=' ', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='departmenthead',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='department_head', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='learner',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='learner', to='accounts.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='accounts.department'),
            preserve_default=False,
        ),
    ]
