# Generated by Django 5.1.1 on 2024-11-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_useractivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Open-Soft Skill', 'Open-Soft Skill'), ('Basic-Technical Skill', 'Basic-Technical Skill'), ('Intermediate-Technical Skill', 'Intermediate-Technical Skill'), ('Advance-Technical Skill', 'Advance-Technical Skill')], max_length=50, null=True),
        ),
    ]
