# Generated by Django 4.2.5 on 2023-11-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_choice_id_alter_progress_id_alter_question_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A description of the quiz",
                verbose_name="Description",
            ),
        ),
    ]
