# Generated by Django 4.2.5 on 2024-02-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_alter_quiz_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitting",
            name="user_answers",
            field=models.TextField(
                blank=True, default="{}", max_length=10000, verbose_name="User Answers"
            ),
        ),
    ]
