# Generated by Django 4.2.5 on 2024-02-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_alter_sitting_user_answers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitting",
            name="user_answers",
            field=models.TextField(
                blank=True, default="{}", verbose_name="User Answers"
            ),
        ),
    ]
