# Generated by Django 4.2.5 on 2024-02-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_alter_sitting_user_answers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitting",
            name="user_answers",
            field=models.TextField(
                blank=True, max_length=100000, null=True, verbose_name="User Answers"
            ),
        ),
    ]
