# Generated by Django 4.2.5 on 2023-11-28 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_courseoffer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="semester",
        ),
        migrations.RemoveField(
            model_name="course",
            name="year",
        ),
        migrations.AddField(
            model_name="course",
            name="language",
            field=models.CharField(
                choices=[
                    ("Hindi", "Hindi"),
                    ("English", "English"),
                    ("Regional", "Regional"),
                ],
                default=django.utils.timezone.now,
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="vertical",
            field=models.IntegerField(
                choices=[("Unit", "Unit"), ("Branch", "Branch")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("Basic", "Basic"),
                    ("Intermediate", "Intermediate"),
                    ("Advance", "Advance"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
