# Generated by Django 4.0.8 on 2024-08-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_course_vertical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='vertical',
            field=models.CharField(choices=[('All', 'All'), ('Unit', 'Unit'), ('Branch', 'Branch')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadvideo',
            name='video',
            field=models.CharField(max_length=50),
        ),
    ]
