# Generated by Django 4.0.8 on 2024-09-16 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_newsandevents_id_alter_semester_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0009_alter_course_vertical_alter_upload_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAllocationLearner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(related_name='learner_course_allocations', to='course.course')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.session')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
