# Generated by Django 5.1.1 on 2024-09-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_courseallocationlearner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvideo',
            name='video',
            field=models.CharField(max_length=100),
        ),
    ]
