# Generated by Django 5.1.1 on 2024-09-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_uploadvideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvideo',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
