# Generated by Django 5.1.1 on 2024-09-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_uploadvideo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=models.CharField(choices=[('Soft Skill', 'Soft Skill'), ('Technical Skill', 'Technical Skill')], default='null', max_length=100),
        ),
    ]
