# Generated by Django 5.1.1 on 2024-10-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_course_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='summary',
            field=models.CharField(choices=[('Soft Skill', 'Soft Skill'), ('Technical Skill', 'Technical Skill')], default='null', max_length=100),
        ),
    ]
