# Generated by Django 5.1.1 on 2024-11-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_program_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Open Soft Skill', 'Open-Techical Skill'), ('Basic-Techical Skill', 'Basic-Techical Skill'), ('Intermediate-Techical Skill', 'Intermediate-Techical Skill'), ('Advance-Techical Skill', 'Advance-Techical Skill')], max_length=50, null=True),
        ),
    ]
