# Generated by Django 5.1.1 on 2024-11-23 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_alter_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseallocationlearner',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
