# Generated by Django 5.1.1 on 2024-11-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_course_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseallocationlearner',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
