# Generated by Django 5.1.1 on 2024-11-27 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_alter_course_timestamp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(help_text='Skill level for the course', max_length=50)),
                ('department', models.CharField(help_text='Department of the team member', max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', help_text='Approval status of the request', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Request creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Request update timestamp')),
                ('course', models.ForeignKey(help_text='Selected course', on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('hod', models.ForeignKey(help_text='HOD making the request', on_delete=django.db.models.deletion.CASCADE, related_name='hod_requests', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(help_text='Selected program', on_delete=django.db.models.deletion.CASCADE, to='course.program')),
                ('team_member', models.ForeignKey(help_text='Team member for whom the request is being made', on_delete=django.db.models.deletion.CASCADE, related_name='team_member_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
